# Generated by Django 6.0.5 on 2026-05-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_uploadlog_file_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadform",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="uploadform",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
