environment           = "prod"
instance_class        = "db.r5.xlarge"
allocated_storage     = 100
storage_type          = "io1"
iops                  = 3000
multi_az              = true
backup_retention_days = 35
max_connections       = "500"
db_username           = "ctms_admin"
db_subnet_group_name  = "<from Section 4 VPC work>"
vpc_id                = "<from Section 4 VPC work>"
app_security_group_id = "<from Section 4 VPC work>"