# Generated by Django 5.2.17 on 2026-09-03 08:42

import datetime

import django.db.models.deletion
from django.db import migrations, models


def seed_plan_catalog(apps, schema_editor):
    """Seed the three default catalog tiers + the single-organization
    subscription, matching defaultSubscription / the SubscriptionEditModal
    tier options in subscriptionService.js exactly so a future frontend
    migration produces byte-identical data. Runs with historical model
    classes (no app imports) per Django data-migration rules.

    price=0 for all seeds: Plan.price is a display-only catalog price tag
    (billing/payments are out of scope for this task), and the frontend
    spec's seed values only pin the limit numbers."""
    Plan = apps.get_model("subscriptions", "Plan")
    Organization = apps.get_model("organizations", "Organization")
    Subscription = apps.get_model("subscriptions", "Subscription")

    seed_plans = [
        # name, max_studies, max_users, storage_limit_gb
        ("Basic", 3, 5, 20),
        ("Professional", 10, 25, 100),
        ("Enterprise", 50, 200, 1000),
    ]
    for name, max_studies, max_users, storage_limit_gb in seed_plans:
        Plan.objects.update_or_create(
            name=name,
            defaults={
                "max_studies": max_studies,
                "max_users": max_users,
                "storage_limit_gb": storage_limit_gb,
                "price": 0,
                "is_active": True,
            },
        )

    # Seed one Subscription for the single existing Organization — or skip
    # fail-soft if no Organization exists yet (multi-tenant deployments
    # will create subscriptions per-org through the API/admin instead).
    organization = Organization.objects.first()
    if organization is None:
        return
    professional = Plan.objects.get(name="Professional")
    Subscription.objects.update_or_create(
        organization=organization,
        defaults={
            "plan": professional,
            "status": "Active",
            "start_date": datetime.date(2026, 1, 1),
            "end_date": datetime.date(2026, 12, 31),
            "auto_renewal": True,
            "notes": "",
        },
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("max_studies", models.PositiveIntegerField()),
                ("max_users", models.PositiveIntegerField()),
                ("storage_limit_gb", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("auto_renewal", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
            ],
        ),
        migrations.RunPython(seed_plan_catalog, migrations.RunPython.noop),
    ]