# Generated by Django 4.2.30 on 2026-09-02 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('redemption_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_bonus_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('referee_days_granted', models.PositiveIntegerField(default=15)),
                ('referrer_days_granted', models.PositiveIntegerField(default=0)),
                ('referee_license_start_date', models.DateTimeField()),
                ('referee_license_end_date', models.DateTimeField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='licensing.referralcode')),
                ('referee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_referral', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successful_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('referral_extension_end_date', models.DateTimeField(blank=True, null=True)),
                ('referral_extension_days_total', models.PositiveIntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('referral_extension_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='licensing.referralusage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_entitlement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
